### ISSUE TITLE
Introductory post is down, link is also (assumed) incorrect in readme

### ISSUE THREAD

**Issue by hook-s3c** [cobbr/SharpGen#3]

**Comment by cobbr** [comment]
Thanks for the heads up @hook-s3c! It's been fixed

**Comment by hook-s3c** [comment]
Thanks!

Link in the content is still broken though;

Intro
You'll find details and motivations for the SharpGen project in this introductory blog post.

**Comment by cobbr** [comment]
Oops! You're right, it was the wrong link. Fixed, thanks again @hook-s3c!
